spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 079ff55baf20b8290387cd7c4503deb8
          google:
            clientId: 203826557370-rd9jogul83srsgngo82v1ej42su1cn5j.apps.googleusercontent.com
            client-secret: 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
          naver:
            client-id: RQiTECeTYqsDjtPrKKh7
            client-secret: H1Di4uMoz2
          facebook:
            client-id: 198781399156968
            client-secret: d5202902d193e9bf400369a42d8a8725
          instagram:
            client-id: 105076125915949
            client-secret: 65d7a62882937f1b91381c980bdac32e

custom:
  security:
    oauth2:
      client:
        registration:
          naver:
            devUserOauthId: '2737088692'
          kakao:
            devUserOauthId: '103240209825008011930'
          google:
            devUserOauthId: '9xIgV-SJgWqRYtj3IX5zCOzvdQdTY2okeb9iXO2Zip4'
          facebook:
            devUserOauthId: '3352084178341521'