spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 079ff55baf20b8290387cd7c4503deb8
          google:
            clientId: 203826557370-rd9jogul83srsgngo82v1ej42su1cn5j.apps.googleusercontent.com
            client-secret: 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